// ---- Talk to your trainer: the agreement ----
// Bump VERSION whenever the terms change in a way a person would want to re-read.
// A stored consent for an older version stops counting, and the sheet appears
// again — that is the whole mechanism, and it is why the version lives here next
// to the text rather than anywhere clever.
//
// Written in plain language on purpose. This is not legal advice and it is not a
// lawyer's document; it is an honest, specific description of what the feature
// does with your data, which is what actually matters both ethically and under
// GDPR (Art. 9 puts health and fitness data in the special category that needs
// explicit consent — which is exactly what this screen collects).

export const TRAINER_AGREEMENT_VERSION = 1;

export interface AgreementSection {
  heading: string;
  body: string;
}

export const TRAINER_AGREEMENT: AgreementSection[] = [
  {
    heading: 'What this is',
    body:
      'Talk to your trainer is an AI chat inside ForgeOS. It answers questions about training, nutrition, recovery and how this app works, using your own data so the answers fit you instead of being generic.',
  },
  {
    heading: 'It is not a doctor',
    body:
      'This is not medical advice. The trainer is not a medical professional, a dietitian or a physiotherapist. For pain, injury, illness, medication or any health worry, talk to a doctor. If something it says contradicts a professional who has actually examined you, believe the professional.',
  },
  {
    heading: 'AI gets things wrong',
    body:
      'Replies are generated by an AI model. It can be confidently incorrect. Treat it like a knowledgeable friend rather than an authority: useful, worth sanity-checking, never a reason to ignore how your body feels.',
  },
  {
    heading: 'What leaves your phone',
    body:
      'When you send a message, that message plus a summary of your ForgeOS data goes to a ForgeOS server (a Cloudflare Worker) and from there to an AI provider to generate the reply. The exact list is shown on this screen before you agree, and it is generated from the same code that builds it — so it cannot quietly drift.',
  },
  {
    heading: 'What never leaves your phone',
    body:
      'Your email address, account id, sign-in provider, friend code, gym location and progress photos are never sent. Only your first name is included, never a full name. Some questions — anything that looks medical, or about disordered eating or banned substances — are answered by the app itself and are never sent anywhere at all.',
  },
  {
    heading: 'Who processes it',
    body:
      'The reply comes from whichever provider is configured on the ForgeOS Worker: Groq, Google Gemini, or Cloudflare Workers AI. Each is a separate company with its own privacy policy, and each may log requests for a period to run and abuse-protect their service. ForgeOS does not store your conversation on any server — it lives on your device.',
  },
  {
    heading: 'Where your chat is stored',
    body:
      'On this device, in the app\'s local storage, so you can scroll back through it. It is included in a ForgeOS backup if you make one. You can delete the whole conversation, and anything you asked the trainer to remember, at any time from the chat screen.',
  },
  {
    heading: 'You are under 18',
    body:
      'ForgeOS knows you are a minor and the trainer is built accordingly: no aggressive deficits, no fasting protocols, no performance-enhancing drugs, no supplement doses beyond ordinary food-level amounts, and no comments on your body. Show this screen to a parent or guardian before you agree — they should know that an AI service processes your fitness data.',
  },
  {
    heading: 'Saying no, and changing your mind',
    body:
      'If you decline, the trainer still works offline: it answers from the app manual and your own numbers, entirely on your device, and sends nothing anywhere. You can withdraw consent whenever you like in Profile → Talk to your trainer, which switches it back to offline mode. Withdrawing does not un-send messages you already sent.',
  },
];

/** The one-line version, for the toggle in Settings. */
export const TRAINER_AGREEMENT_SUMMARY =
  'Sends your message and a summary of your ForgeOS data to an AI provider to generate replies. Not medical advice. Decline and the trainer still works offline, on-device.';
